# Generated by Django 2.1.7 on 2019-10-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='Project Name')),
                ('project_short_name', models.CharField(max_length=5, verbose_name='Project Short Name')),
                ('project_id', models.CharField(max_length=5, verbose_name='Project ID')),
                ('project_code', models.CharField(max_length=5, unique=True, verbose_name='Project Code')),
                ('project_register_type', models.CharField(choices=[(1, 'Company'), (2, 'Individual'), (3, 'Group')], max_length=5, verbose_name='Project Register Type')),
                ('project_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Project Start Date')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('project_type', models.IntegerField(choices=[(1, 'Web/Mobile development'), (2, 'Image Processing'), (3, 'CMS'), (4, 'AWS Management'), (5, 'Machine Learning')], default=1, verbose_name='Project Type')),
                ('default_address_level', models.IntegerField(choices=[(1, 'simple'), (2, 'intermediate'), (3, 'detail')], default=1, verbose_name='Project Address Level')),
                ('project_suburb', models.CharField(blank=True, max_length=5, verbose_name='Project Suburb')),
                ('project_state', models.CharField(blank=True, max_length=5, verbose_name='Project State')),
                ('project_post_code', models.CharField(blank=True, max_length=5, verbose_name='Project Post Code')),
                ('project_country', models.CharField(choices=[('DE', 'Germany'), ('US', 'United States'), ('CN', 'China'), ('JP', 'Japan'), ('FR', 'France'), ('UR', 'Ukraine'), ('IN', 'India')], max_length=3, verbose_name='Project Country')),
                ('address1', models.CharField(blank=True, max_length=64, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, max_length=64, verbose_name='Address2')),
                ('address3', models.CharField(blank=True, max_length=64, verbose_name='Address3')),
                ('project_description', models.TextField(verbose_name='Project Description')),
            ],
        ),
    ]
