# Generated by Django 2.1.7 on 2020-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneCode', models.CharField(max_length=5)),
                ('alpha2code', models.CharField(max_length=5)),
                ('alpha3code', models.CharField(max_length=5)),
                ('flag', models.FileField(blank=True, null=True, upload_to='static/images/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
