# Generated by Django 2.1.7 on 2020-01-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200118_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=5)),
                ('counts', models.IntegerField(default=0)),
            ],
        ),
    ]
