# Generated by Django 2.1.7 on 2020-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_githubuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='skills',
            field=models.CharField(max_length=255),
        ),
    ]
