# Generated by Django 2.1.7 on 2020-01-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200118_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='githubusers', to='management.Country'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='counts',
            field=models.IntegerField(default=0, verbose_name='The number of Repositories'),
        ),
    ]
